version: "3.8"

services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:///url_shortener.db
      - BASE_URL=http://localhost:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
